const express = require('express');
const cors = require('cors');

const app = express();

// Middleware
app.use(cors()); // Allows requests from other origins
app.use(express.json()); // Parses incoming JSON data

// Predefined set of questions and answers about underwater life
// HERE
const questionsAndAnswers = [
  { question: 'What is sealife?', reply: 'Sealife refers to all organisms that live in the sea, including fish, mammals, plants, and microorganisms.' },
  { question: 'hello', reply: 'Welcome to SeaBot-A customised chatBot of AquaInsights ' },
  { question: 'Hi', reply: 'Hello! How can I assist you today?' },
  { question: 'hello', reply: 'Hi there! What can I help you with?' },
  { question: 'How can you help me?', reply: 'I can provide information about marine life, the effects of pollution, and insights about aquatic ecosystems. Feel free to ask!' },
  { question: 'What is Aqua Insights?', reply: 'Aqua Insights is a platform that simulates the effects of pollutants on marine life and provides information about locations like mangrove forests in India, their species, and their food chains.' },
  { question: 'What are mangrove forests?', reply: 'Mangrove forests are coastal wetlands found in tropical and subtropical regions. They act as a habitat for many species and help protect coastlines from erosion.' },
  { question: 'What species live in mangrove forests?', reply: 'Mangrove forests host species like mudskippers, mangrove snappers, and crabs, all part of a unique and interconnected food chain.' },
  { question: 'What is the food chain in mangrove forests?', reply: 'In mangrove forests, the food chain starts with decomposed organic matter consumed by small invertebrates, followed by fish, crabs, and larger predators like birds or larger fish.' },
  { question: 'How do pollutants affect mangroves?', reply: 'Pollutants like chemicals and waste damage the delicate ecosystem of mangroves by reducing water quality, harming species, and disrupting the food chain.' },
  { question: 'What happens when chemicals enter the sea?', reply: 'Chemicals can cause oxygen depletion, harm marine organisms, and disrupt ecosystems, leading to dead zones in water bodies.' },
  { question: 'Why are mangroves important?', reply: 'Mangroves provide critical habitats, act as natural storm barriers, and absorb carbon, helping combat climate change.' },
  { question: 'What can I do to protect marine life?', reply: 'You can reduce single-use plastics, support sustainable seafood, participate in beach cleanups, and raise awareness about marine conservation.' },
  { question: 'How do pollutants affect fish?', reply: 'Pollutants can impair fish growth, reproduction, and survival. Long-term exposure can lead to population decline.' },
  { question: 'What is the largest sea creature?', reply: 'The blue whale is the largest sea creature, reaching lengths of up to 100 feet.' },
  { question: 'What are coral reefs?', reply: 'Coral reefs are underwater ecosystems made up of coral polyps held together by calcium carbonate. They are home to a wide variety of marine life.' },
  { question: 'What is plankton?', reply: 'Plankton are microscopic organisms that float in the ocean. They are a crucial part of the marine food chain.' },
  { question: 'Why is the ocean salty?', reply: 'The ocean is salty due to minerals and salts that are washed into it from rivers and the seafloor.' },
  { question: 'What are the different ocean zones?', reply: 'The ocean is divided into zones: epipelagic (sunlight), mesopelagic (twilight), bathypelagic (midnight), abyssopelagic (abyssal), and hadalpelagic (trenches).' },
  { question: 'What is the importance of mangroves?', reply: 'Mangroves are coastal ecosystems that protect shorelines, provide habitat for marine life, and store carbon.' },
  { question: 'How do fish breathe underwater?', reply: 'Fish breathe underwater using gills, which extract oxygen from water.' },
  { question: 'What are the main threats to underwater life?', reply: 'Pollution, overfishing, habitat destruction, and climate change are major threats to underwater life.' },
  { question: 'What is ocean acidification?', reply: 'Ocean acidification occurs when CO2 dissolves in seawater, lowering its pH and harming marine organisms.' },
  { question: 'How do dolphins breathe?', reply: 'Dolphins breathe through their blowholes at the surface of the water. They must come up for air approximately every 30 seconds to a few minutes.' },
  { question: 'How do sea otters use tools?', reply: 'Sea otters use tools, such as rocks, to break open shellfish like clams and sea urchins. They often use their stomachs as anvils to crack open their food.' },
  { question: 'How do sharks sleep?', reply: 'Sharks don’t sleep like humans, but they do enter rest periods where part of their brain stays active while they keep swimming. Some species need to keep moving to breathe.' },
  { question: 'How do seahorses mate?', reply: 'Seahorses mate in a unique courtship dance, where the male seahorse carries the female’s eggs in his brood pouch until they hatch.' },
  { question: 'How do manta rays give birth?', reply: 'Manta rays give birth to live young after a gestation period of about a year. They give birth to one pup at a time, which is already quite large.' },
  { question: 'How do fish breathe underwater?', reply: 'Fish breathe underwater through their gills, which extract oxygen from water as it flows over them.' },
  { question: 'How do seahorses protect their young?', reply: 'Male seahorses protect their young by carrying the eggs in a specialized pouch until they hatch. After birth, the tiny seahorses are left to fend for themselves.' },
  { question: 'How do deep-sea fish survive without sunlight?', reply: 'Deep-sea fish survive without sunlight by relying on bioluminescence to find food and communicate. They also adapt to extreme pressure and cold.' },
  { question: 'How do jellyfish avoid predators?', reply: 'Jellyfish avoid predators by using their stinging cells (nematocysts) to defend themselves. Some species also use their transparency to blend in with the water.' },
  { question: 'How do lobsters shed their shells?', reply: 'Lobsters molt to shed their exoskeletons in order to grow. They usually do this several times in their lifetime.' },
  { question: 'How do starfish regenerate lost arms?', reply: 'Starfish can regenerate lost arms by growing new ones from the central disk. This process can take several months, depending on the species.' },
  { question: 'How do octopuses escape predators?', reply: 'Octopuses escape predators by using camouflage, squeezing through tight spaces, and even releasing ink to create a smokescreen for a quick getaway.' },
  { question: 'How do clams form pearls?', reply: 'Clams form pearls when an irritant, like a grain of sand, gets inside their shells. The clam secretes layers of nacre around the irritant, eventually forming a pearl.' },
  { question: 'How do squids use their tentacles to catch food?', reply: 'Squids use their long, flexible tentacles to catch prey. They grab their food, then use their beak-like mouth to consume it.' },
  { question: 'How do coral reefs grow?', reply: 'Coral reefs grow through the accumulation of calcium carbonate secreted by coral polyps. Over time, they build large, vibrant structures that provide habitats for many species.' },
  { question: 'How do fish communicate?', reply: 'Fish communicate using visual signals, sounds, and chemical cues. Some fish also use electric fields to communicate with each other.' },
  { question: 'How do sea lions swim?', reply: 'Sea lions swim by using their large front flippers to propel themselves and their back flippers to steer. This allows them to move quickly and gracefully through the water.' },
  { question: 'How do sea urchins feed?', reply: 'Sea urchins feed by grazing on algae, using a specialized feeding structure called Aristotle’s lantern to scrape algae from rocks.' },
  { question: 'How do dolphins find food?', reply: 'Dolphins use echolocation to locate food, emitting clicks and listening for the echoes that bounce off objects in the water.' },
  { question: 'How do whales communicate with each other?', reply: 'Whales communicate through vocalizations like songs, clicks, and whistles, which can travel long distances underwater.' },
  { question: 'How do seagulls find food?', reply: 'Seagulls are opportunistic feeders and will search for food in coastal areas, picking up small fish, scavenging from human activity, or even stealing food from other birds.' },
  { question: 'How do sea slugs protect themselves?', reply: 'Sea slugs protect themselves by producing toxic chemicals or by feeding on toxic algae, incorporating the toxins into their own bodies for defense.' },
  { question: 'How do manatees survive in cold water?', reply: 'Manatees have thick layers of fat and fur to insulate them from cold water. They seek warm-water refuges during winter to avoid the dangers of cold stress.' },
  { question: 'How do jellyfish reproduce?', reply: 'Jellyfish reproduce both sexually and asexually. In the sexual phase, males release sperm, and females release eggs. After fertilization, larvae develop into polyps.' },
  { question: 'How do whales find their food in the deep ocean?', reply: 'Whales use echolocation to find prey, such as fish or squid, in deep waters where visibility is low. This ability allows them to hunt efficiently in the dark depths of the ocean.' },
  { question: 'How do squid camouflage?', reply: 'Squid can change color and texture to blend into their environment using special cells in their skin called chromatophores.' },
  { question: 'How do shrimp protect themselves from predators?', reply: 'Shrimp use their speed to escape predators, and some species can also hide in crevices or use camouflage to avoid detection.' },
  { question: 'How do crabs mate?', reply: 'Crabs mate through a process where the male grabs the female and fertilizes her eggs. After fertilization, the female carries the eggs until they hatch.' },
  { question: 'How do whales avoid predators?', reply: 'Whales avoid predators like orcas by using their size, speed, and social groups. Some species also use deep dives to escape danger.' },
  { question: 'How do dolphins use echolocation?', reply: 'Dolphins use echolocation to locate prey and navigate through murky waters by emitting sound waves and listening to the echoes.' },
  { question: 'How do coral reefs benefit marine life?', reply: 'Coral reefs provide a habitat for thousands of marine species, offering shelter, food, and protection. They are essential for biodiversity in the oceans.' },
  { question: 'How do sea horses protect their young?', reply: 'Male seahorses protect their young by carrying the fertilized eggs in a brood pouch until they hatch, ensuring their survival.' },
  { question: 'How do sea turtles migrate?', reply: 'Sea turtles migrate thousands of miles between feeding grounds and nesting beaches. They use the Earth’s magnetic field to navigate across the oceans.' },
  { question: 'How do octopuses camouflage themselves?', reply: 'Octopuses can change the color, texture, and pattern of their skin using specialized cells called chromatophores and papillae. This allows them to blend in perfectly with their surroundings.' },
  { question: 'How do jellyfish sting?', reply: 'Jellyfish have specialized cells called nematocysts on their tentacles, which contain tiny harpoons filled with venom. When they come into contact with prey or a threat, these cells fire, injecting venom.' },
  { question: 'How do sharks reproduce?', reply: 'Sharks reproduce through internal fertilization. Depending on the species, they may lay eggs (oviparous) or give birth to live young (viviparous).' },
  { question: 'How do dolphins hunt together?', reply: 'Dolphins hunt cooperatively in groups by herding schools of fish into tight clusters and taking turns feeding. They communicate and coordinate to maximize their hunting success.' },
  { question: 'How do whales communicate over long distances?', reply: 'Whales communicate with long-range vocalizations called songs, especially in baleen whales. These songs can travel for miles underwater, allowing communication over vast distances.' },
  { question: 'How do squids move in the water?', reply: 'Squids use jet propulsion to move through the water. They expel water from a siphon, propelling themselves in the opposite direction. This allows them to move quickly and evade predators.' },
  { question: 'How do sea horses change color?', reply: 'Seahorses can change color by adjusting the pigmentation in their skin, often to blend into their environment or to communicate with other seahorses.' },
  { question: 'How do starfish move?', reply: 'Starfish move using tube feet located on the underside of their bodies. These feet operate like suction cups, allowing them to slowly crawl along the ocean floor.' },
  { question: 'How do hermit crabs find new shells?', reply: 'Hermit crabs search for new shells as they grow. They often exchange shells with other crabs in a process called "shell swapping," ensuring they find a comfortable fit.' },
  { question: 'How do manatees find food in the water?', reply: 'Manatees are herbivores and spend most of their time grazing on seagrasses and aquatic plants. They use their sensitive whiskers to locate plants in the murky waters.' },
  { question: 'How do whales use their baleen plates to feed?', reply: 'Baleen whales feed by taking in large mouthfuls of water. ' },
  { question: 'How do whales use their baleen plates to feed?', reply: 'Baleen whales feed by taking in large mouthfuls of water and then pushing the water out through their baleen plates, trapping small organisms like krill and plankton inside.' },
  { question: 'How do sea otters keep warm in cold water?', reply: 'Sea otters have a thick layer of fur that keeps them insulated, trapping air close to their bodies. Unlike most marine mammals, they don’t have blubber but rely on their fur to stay warm.' },
  { question: 'How do deep-sea fish find food in the dark?', reply: 'Deep-sea fish rely on bioluminescence to find food in the pitch-black depths of the ocean. They may produce their own light or rely on the light from other organisms.' },
  { question: 'How do octopuses escape from enclosures?', reply: 'Octopuses are known for their problem-solving abilities. They can escape enclosures by unscrewing lids, squeezing through small gaps, and even using tools.' },
  { question: 'How do sea lions hunt for food?', reply: 'Sea lions hunt in groups and use their agility in the water to catch fish and squid. They are also capable of diving to considerable depths to find prey.' },
  { question: 'How do dolphins use tools?', reply: 'Some dolphins use tools, such as sea sponges, to protect their rostrums (snouts) while foraging on the ocean floor. This behavior is learned and passed down through generations.' },
  { question: 'How do rays protect themselves?', reply: 'Rays use their flattened bodies to hide in the sand or mud, where they can avoid predators. Some species, like stingrays, also have venomous barbs to defend themselves.' },
  { question: 'How do sharks detect prey through the water?', reply: 'Sharks can detect prey using electroreception. They have special sensors called ampullae of Lorenzini that can detect the electrical fields produced by the movements of living animals.' },
  { question: 'How do sea urchins move?', reply: 'Sea urchins move slowly across the ocean floor using their tube feet, which extend from the underside of their bodies. These feet operate through hydraulic pressure.' },
  { question: 'How do squids reproduce?', reply: 'Squids reproduce through internal fertilization. The male transfers sperm to the female via a specialized arm called a hectocotylus. After fertilization, the female lays eggs in a safe location.' },
  { question: 'How do coral reefs benefit from symbiosis?', reply: 'Coral reefs thrive due to the symbiotic relationship between coral polyps and algae called zooxanthellae. The algae provide nutrients to the corals through photosynthesis, while the corals provide a safe home for the algae.' },
  { question: 'How do humpback whales feed?', reply: 'Humpback whales use a unique feeding technique called "bubble net feeding." They create bubbles to corral schools of fish and then swim up through the bubbles to scoop up the fish.' },
  { question: 'How do jellyfish travel across the ocean?', reply: 'Jellyfish travel through the water by pulsating their bell, pushing water behind them. While they can move actively, much of their movement is also influenced by ocean currents.' },
  { question: 'How do narwhals use their tusks?', reply: 'Narwhals use their tusks for a variety of purposes, including communication, dominance displays, and possibly to detect changes in water pressure.' },
  { question: 'How do sea snakes defend themselves?', reply: 'Sea snakes defend themselves through venom, which they use to immobilize prey. Some species also rely on camouflage to avoid detection by predators.' },
  { question: 'How do anemones capture prey?', reply: 'Anemones capture prey by using their stinging tentacles, which paralyze and entangle small fish and invertebrates. The venom from the tentacles helps immobilize their prey.' },
  { question: 'How do sea urchins reproduce?', reply: 'Sea urchins reproduce by releasing eggs and sperm into the water, where fertilization occurs externally. The fertilized eggs develop into larvae, which eventually settle on the ocean floor.' },
  { question: 'How do dolphins sleep?', reply: 'Dolphins sleep by resting one hemisphere of their brain at a time, allowing them to remain partially alert and continue swimming.' },
  { question: 'How do sea turtles migrate?', reply: 'Sea turtles migrate thousands of miles between feeding grounds and nesting beaches. They use the Earth’s magnetic field to navigate across the oceans.' },
  { question: 'How do octopuses camouflage themselves?', reply: 'Octopuses can change the color, texture, and pattern of their skin using specialized cells called chromatophores and papillae. This allows them to blend in perfectly with their surroundings.' },
  { question: 'How do jellyfish sting?', reply: 'Jellyfish have specialized cells called nematocysts on their tentacles, which contain tiny harpoons filled with venom. When they come into contact with prey or a threat, these cells fire, injecting venom.' },
  { question: 'How do sharks reproduce?', reply: 'Sharks reproduce through internal fertilization. Depending on the species, they may lay eggs (oviparous) or give birth to live young (viviparous).' },
  { question: 'How do dolphins hunt together?', reply: 'Dolphins hunt cooperatively in groups by herding schools of fish into tight clusters and taking turns feeding. They communicate and coordinate to maximize their hunting success.' },
  { question: 'How do whales communicate over long distances?', reply: 'Whales communicate with long-range vocalizations called songs, especially in baleen whales. These songs can travel for miles underwater, allowing communication over vast distances.' },
  { question: 'How do squids move in the water?', reply: 'Squids use jet propulsion to move through the water. They expel water from a siphon, propelling themselves in the opposite direction. This allows them to move quickly and evade predators.' },
  { question: 'How do sea horses change color?', reply: 'Seahorses can change color by adjusting the pigmentation in their skin, often to blend into their environment or to communicate with other seahorses.' },
  { question: 'How do starfish move?', reply: 'Starfish move using tube feet located on the underside of their bodies. These feet operate like suction cups, allowing them to slowly crawl along the ocean floor.' },
  { question: 'How do hermit crabs find new shells?', reply: 'Hermit crabs search for new shells as they grow. They often exchange shells with other crabs in a process called "shell swapping," ensuring they find a comfortable fit.' },
  { question: 'How do manatees find food in the water?', reply: 'Manatees are herbivores and spend most of their time grazing on seagrasses and aquatic plants. They use their sensitive whiskers to locate plants in the murky waters.' },
  { question: 'How do whales use their baleen plates to feed?', reply: 'Baleen whales feed by taking in large mouthfuls of water and then pushing the water out through their baleen plates, trapping small organisms like krill and plankton inside.' },
  { question: 'How do sea otters keep warm in cold water?', reply: 'Sea otters have a thick layer of fur that keeps them insulated, trapping air close to their bodies. Unlike most marine mammals, they don’t have blubber but rely on their fur to stay warm.' },
  { question: 'How do deep-sea fish find food in the dark?', reply: 'Deep-sea fish rely on bioluminescence to find food in the pitch-black depths of the ocean. They may produce their own light or rely on the light from other organisms.' },
  { question: 'How do octopuses escape from enclosures?', reply: 'Octopuses are known for their problem-solving abilities. They can escape enclosures by unscrewing lids, squeezing through small gaps, and even using tools.' },
  { question: 'How do sea lions hunt for food?', reply: 'Sea lions hunt in groups and use their agility in the water to catch fish and squid. They are also capable of diving to considerable depths to find prey.' },
  { question: 'How do dolphins use tools?', reply: 'Some dolphins use tools, such as sea sponges, to protect their rostrums (snouts) while foraging on the ocean floor. This behavior is learned and passed down through generations.' },
  { question: 'How do rays protect themselves?', reply: 'Rays use their flattened bodies to hide in the sand or mud, where they can avoid predators. Some species, like stingrays, also have venomous barbs to defend themselves.' },
  { question: 'How do sharks detect prey through the water?', reply: 'Sharks can detect prey using electroreception. They have special sensors called ampullae of Lorenzini that can detect the electrical fields produced by the movements of living animals.' },
  { question: 'How do sea urchins move?', reply: 'Sea urchins move slowly across the ocean floor using their tube feet, which extend from the underside of their bodies. These feet operate through hydraulic pressure.' },
  { question: 'How do squids reproduce?', reply: 'Squids reproduce through internal fertilization. The male transfers sperm to the female via a specialized arm called a hectocotylus. After fertilization, the female lays eggs in a safe location.' },
  { question: 'How do coral reefs benefit from symbiosis?', reply: 'Coral reefs thrive due to the symbiotic relationship. ' },
  { question: 'How do coral reefs benefit from symbiosis?', reply: 'Coral reefs thrive due to the symbiotic relationship between coral polyps and algae called zooxanthellae. The algae provide nutrients to the corals through photosynthesis, while the corals provide a safe home for the algae.' },
  { question: 'How do humpback whales feed?', reply: 'Humpback whales use a unique feeding technique called "bubble net feeding." They create bubbles to corral schools of fish and then swim up through the bubbles to scoop up the fish.' },
  { question: 'How do jellyfish travel across the ocean?', reply: 'Jellyfish travel through the water by pulsating their bell, pushing water behind them. While they can move actively, much of their movement is also influenced by ocean currents.' },
  { question: 'How do narwhals use their tusks?', reply: 'Narwhals use their tusks for a variety of purposes, including communication, dominance displays, and possibly to detect changes in water pressure.' },
  { question: 'How do sea snakes defend themselves?', reply: 'Sea snakes defend themselves through venom, which they use to immobilize prey. Some species also rely on camouflage to avoid detection by predators.' },
  { question: 'How do anemones capture prey?', reply: 'Anemones capture prey by using their stinging tentacles, which paralyze and entangle small fish and invertebrates. The venom from the tentacles helps immobilize their prey.' },
  { question: 'How do sea urchins reproduce?', reply: 'Sea urchins reproduce by releasing eggs and sperm into the water, where fertilization occurs externally. The fertilized eggs develop into larvae, which eventually settle on the ocean floor.' },
  { question: 'How do dolphins sleep?', reply: 'Dolphins sleep by resting one hemisphere of their brain at a time, allowing them to remain partially alert and continue swimming.' },
  { question: 'How do sea turtles migrate?', reply: 'Sea turtles migrate thousands of miles between feeding grounds and nesting beaches. They use the Earth’s magnetic field to navigate across the oceans.' },
  { question: 'How do octopuses camouflage themselves?', reply: 'Octopuses can change the color, texture, and pattern of their skin using specialized cells called chromatophores and papillae. This allows them to blend in perfectly with their surroundings.' },
  { question: 'How do jellyfish sting?', reply: 'Jellyfish have specialized cells called nematocysts on their tentacles, which contain tiny harpoons filled with venom. When they come into contact with prey or a threat, these cells fire, injecting venom.' },
  { question: 'How do sharks reproduce?', reply: 'Sharks reproduce through internal fertilization. Depending on the species, they may lay eggs (oviparous) or give birth to live young (viviparous).' },
  { question: 'How do dolphins hunt together?', reply: 'Dolphins hunt cooperatively in groups by herding schools of fish into tight clusters and taking turns feeding. They communicate and coordinate to maximize their hunting success.' },
  { question: 'How do whales communicate over long distances?', reply: 'Whales communicate with long-range vocalizations called songs, especially in baleen whales. These songs can travel for miles underwater, allowing communication over vast distances.' },
  { question: 'How do squids move in the water?', reply: 'Squids use jet propulsion to move through the water. They expel water from a siphon, propelling themselves in the opposite direction. This allows them to move quickly and evade predators.' },
  { question: 'How do sea horses change color?', reply: 'Seahorses can change color by adjusting the pigmentation in their skin, often to blend into their environment or to communicate with other seahorses.' },
  { question: 'How do starfish move?', reply: 'Starfish move using tube feet located on the underside of their bodies. These feet operate like suction cups, allowing them to slowly crawl along the ocean floor.' },
  { question: 'How do hermit crabs find new shells?', reply: 'Hermit crabs search for new shells as they grow. They often exchange shells with other crabs in a process called "shell swapping," ensuring they find a comfortable fit.' },
  { question: 'How do manatees find food in the water?', reply: 'Manatees are herbivores and spend most of their time grazing on seagrasses and aquatic plants. They use their sensitive whiskers to locate plants in the murky waters.' },
  { question: 'How do whales use their baleen plates to feed?', reply: 'Baleen whales feed by taking in large mouthfuls of water and then pushing the water out through their baleen plates, trapping small organisms like krill and plankton inside.' },
  { question: 'How do sea otters keep warm in cold water?', reply: 'Sea otters have a thick layer of fur that keeps them insulated, trapping air close to their bodies. Unlike most marine mammals, they don’t have blubber but rely on their fur to stay warm.' },
  { question: 'How do deep-sea fish find food in the dark?', reply: 'Deep-sea fish rely on bioluminescence to find food in the pitch-black depths of the ocean. They may produce their own light or rely on the light from other organisms.' },
  { question: 'How do octopuses escape from enclosures?', reply: 'Octopuses are known for their problem-solving abilities. They can escape enclosures by unscrewing lids, squeezing through small gaps, and even using tools.' },
  { question: 'How do sea lions hunt for food?', reply: 'Sea lions hunt in groups and use their agility in the water to catch fish and squid. They are also capable of diving to considerable depths to find prey.' },
  { question: 'How do dolphins use tools?', reply: 'Some dolphins use tools, such as sea sponges, to protect their rostrums (snouts) while foraging on the ocean floor. This behavior is learned and passed down through generations.' },
  { question: 'How do rays protect themselves?', reply: 'Rays use their flattened bodies to hide in the sand or mud, where they can avoid predators. Some species, like stingrays, also have venomous barbs to defend themselves.' },
  { question: 'How do sharks detect prey through the water?', reply: 'Sharks can detect prey using electroreception. They have special sensors called ampullae of Lorenzini that can detect the electrical fields produced by the movements of living animals.' },
  { question: 'How do sea urchins move?', reply: 'Sea urchins move slowly across the ocean floor using their tube feet, which extend from the underside of their bodies. These feet operate through hydraulic pressure.' },
  { question: 'How do squids reproduce?', reply: 'Squids reproduce through internal fertilization. The male transfers sperm to the female via a specialized arm called a hectocotylus. After fertilization, the female lays eggs in a safe location.' },
  { question: 'How do coral reefs benefit from symbiosis?', reply: 'Coral reefs thrive due to the symbiotic relationship between coral polyps and algae called zooxanthellae. The algae provide nutrients to the corals through photosynthesis, while the corals provide a safe home for the algae.' },
  { question: 'How do humpback whales feed?', reply: 'Humpback whales use a unique feeding technique called "bubble net feeding." They create bubbles to corral schools of fish and then swim up through the bubbles to scoop up the fish.' },
  { question: 'How do jellyfish travel across the ocean?', reply: 'Jellyfish travel through the water by pulsating their bell, pushing water behind them. While they can move actively, much of their movement is also influenced by ocean currents.' },
  { question: 'How do narwhals use their tusks?', reply: 'Narwhals use their tusks for a variety of purposes, including communication, dominance displays, and possibly to detect changes in water pressure.' },
  { question: 'How do sea snakes defend themselves?', reply: 'Sea snakes defend themselves through venom, which they use to immobilize prey. Some species also rely on camouflage to avoid detection by predators.' },
  { question: 'How do anemones capture prey?', reply: 'Anemones capture prey by using their stinging tentacles, which paralyze and entangle small fish and invertebrates. The venom from the tentacles helps immobilize their prey.' },
  { question: 'How do sea lions communicate?', reply: 'Sea lions communicate through vocalizations such as barks, roars, and growls. They also use body language, such as postures and movements, to signal aggression, dominance, or mating readiness.' },
  { question: 'How do manta rays feed?', reply: 'Manta rays feed by swimming with their mouths open, filtering plankton and small fish from the water. They use their cephalic lobes to funnel food into their mouths as they swim through large volumes of water.' },
  { question: 'How do seahorses swim?', reply: 'Seahorses swim upright by using a small dorsal fin on their back to propel themselves. They also use their pectoral fins near their heads to steer and navigate through the water.' },
  { question: 'How do sea turtles protect themselves?', reply: 'Sea turtles rely on their hard, protective shells to shield themselves from predators. When threatened, they may retreat into their shells or use speed to escape.' },
  { question: 'How do killer whales hunt?', reply: 'Killer whales, or orcas, hunt in coordinated groups. They use teamwork and sophisticated hunting techniques, such as herding fish, creating waves to knock seals off ice floes, or even beaching themselves temporarily to capture prey.' },
  { question: 'How do octopuses defend themselves?', reply: 'Octopuses use a variety of defense mechanisms including camouflage, ink ejection, and hiding in crevices or burrows to escape predators. Some species can also detach their arms to distract attackers while they escape.' },
  { question: 'How do dolphins feed?', reply: 'Dolphins feed by hunting in groups, often using cooperative strategies like herding schools of fish into tight groups before taking turns to catch the prey. They may also use echolocation to locate their food.' },
  { question: 'How do jellyfish reproduce?', reply: 'Jellyfish reproduce through both sexual and asexual reproduction. Most species have a two-stage lifecycle: a medusa stage (adult form) that produces eggs and sperm, and a polyp stage that can clone itself.' },
  { question: 'How do starfish move on land?', reply: 'Starfish typically do not move on land, but they can crawl across the ocean floor using their tube feet. These feet, located on the underside of their bodies, help them move and attach to surfaces.' },
  { question: 'How do sea horses camouflage?', reply: 'Seahorses camouflage by changing their color and texture to blend in with their surroundings, such as seaweed or coral. Their camouflage helps them avoid predators.' },
  { question: 'How do sea slugs protect themselves?', reply: 'Sea slugs protect themselves by using chemical defenses, such as toxins, that they produce or absorb from their environment. Some species also rely on camouflage to hide from predators.' },
  { question: 'How do manta rays migrate?', reply: 'Manta rays migrate over vast distances, often following ocean currents and food availability. They travel in groups, often crossing entire ocean basins to find breeding or feeding grounds.' },
  { question: 'How do dolphins communicate?', reply: 'Dolphins communicate through a wide range of vocalizations including clicks, whistles, and body language. They use these sounds for navigation, hunting, and maintaining social bonds with each other.' },
  { question: 'How do humpback whales protect their calves?', reply: 'Humpback whales protect their calves by keeping them close and shielding them from potential predators, such as orcas. The mother and other adult whales in the group will often form a protective barrier around the calf.' },
  { question: 'How do sea stars feed?', reply: 'Sea stars are carnivorous and feed by extending their stomachs out through their mouths to engulf prey such as bivalves. They secrete digestive enzymes to break down the prey outside their bodies before ingesting it.' },
  { question: 'How do sharks find food in the dark?', reply: 'Sharks use their acute sense of smell to detect prey, even in the dark. They also rely on electroreception to sense the electrical fields created by animals’ movements in the water.' },
  { question: 'How do whales stay warm in cold water?', reply: 'Whales stay warm in cold water through a thick layer of blubber that insulates their bodies. This layer helps them retain heat, even in freezing Arctic waters.' },
  { question: 'How do sea otters hold hands?', reply: 'Sea otters hold hands while resting or sleeping to prevent drifting apart. This behavior is especially important when they float in kelp forests, which act as anchor points to keep them from drifting away in the current.' },
  { question: 'How do manatees eat?', reply: 'Manatees are herbivores and feed primarily on aquatic plants like seagrasses. They use their prehensile lips to grasp and pull vegetation toward their mouths, and they can eat up to 10% of their body weight in a day.' },
  { question: 'How do fish breathe?', reply: 'Fish breathe by taking water in through their mouths and passing it over their gills. The gills extract oxygen from the water and expel carbon dioxide in exchange, allowing the fish to stay oxygenated.' },
  { question: 'How do penguins stay warm?', reply: 'Penguins stay warm by having a thick layer of feathers and a layer of fat beneath their skin. These adaptations help to insulate them from the cold, especially in frigid Antarctic waters.' },
  { question: 'How do clams filter food?', reply: 'Clams filter food from the water by drawing water into their shells. They use specialized gills to trap plankton and other small particles, which they then pass into their mouths to eat.' },
  { question: 'How do crabs grow?', reply: 'Crabs grow by molting, a process where they shed their old exoskeleton to reveal a larger, soft one beneath. After molting, the new exoskeleton hardens over time, allowing the crab to continue growing.' },
  { question: 'How do dolphins protect their young?', reply: 'Dolphins protect their young by keeping them in the center of the group during travel, allowing adults to form a barrier around the calf. They may also use their powerful tails to fend off threats.' },
  { question: 'How do orcas communicate?', reply: 'Orcas communicate using a complex system of clicks, whistles, and body language. They also use echolocation for hunting and navigation, helping them locate prey even in dark or murky waters.' },
  { question: 'How do sea horses protect their young?', reply: 'Seahorses do not protect their young after birth. However, the male seahorse protects the fertilized eggs in his brood pouch until they hatch. Once born, the baby seahorses are independent.' },
  { question: 'How do sea otters eat shellfish?', reply: 'Sea otters use rocks or other hard objects as tools to crack open shellfish. They float on their backs and use their chests as anvils, smashing the shells open to access the meat inside.' },
  { question: 'How do rays reproduce?', reply: 'Rays reproduce through internal fertilization. After mating, the female lays eggs or gives birth to live young, depending on the species. Some rays, like stingrays, give birth to live young.' },
  { question: 'How do hermit crabs grow?', reply: 'Hermit crabs grow by shedding their exoskeleton (a process called molting) and moving into a larger shell. As they grow, they search for new shells that fit their increasing size.' },
  { question: 'How do sea otters stay afloat?', reply: 'Sea otters stay afloat by using a thick layer of fur that traps air, providing buoyancy. Unlike most marine mammals, they don’t have blubber, relying instead on their fur to keep them warm and afloat.' },
  { question: 'How do sea horses reproduce?', reply: 'Seahorses reproduce through a unique process where the male carries the fertilized eggs in a pouch on his abdomen until they hatch. After incubation, the male gives birth to fully formed baby seahorses.' },
  { question: 'How do starfish regenerate lost limbs?', reply: 'Starfish can regenerate lost arms as long as part of the central disc remains intact. They grow back their limbs over time, a process that can take weeks to months depending on the species.' },
  { question: 'How do hermit crabs find new shells?', reply: 'Hermit crabs find new shells by seeking out abandoned shells from other marine animals. They will often engage in "shell exchanges," where several crabs line up and swap shells for larger ones.' },
  { question: 'How do manatees communicate?', reply: 'Manatees communicate with each other through a variety of vocalizations such as whistles, squeals, and chirps. They also use body language, such as rubbing against each other or postures to express aggression or affection.' },
  { question: 'How do whales use their baleen plates to filter food?', reply: 'Baleen whales use their comb-like baleen plates to filter tiny prey like krill from seawater. They take in a large gulp of water and then expel it through the baleen, trapping food inside for consumption.' },
  { question: 'How do sea otters use tools?', reply: 'Sea otters are known to use rocks and other hard objects as tools. They use these tools to crack open shellfish and clams, floating on their backs and using their chests as anvils.' },
  { question: 'How do deep-sea fish survive in the dark?', reply: 'Deep-sea fish have adapted to the lack of light by developing bioluminescence, which helps them attract prey, communicate, or camouflage themselves in the dark depths of the ocean.' },
  { question: 'How do octopuses escape from predators?', reply: 'Octopuses are incredibly flexible and can squeeze through very small gaps. They use their soft bodies and camouflage abilities to escape predators or evade capture in confined spaces.' },
  { question: 'How do sea lions catch fish?', reply: 'Sea lions use their speed and agility in the water to chase fish and squid. They often hunt in groups, using coordinated tactics to herd fish into tight schools before catching them.' },
  { question: 'How do dolphins use echolocation?', reply: 'Dolphins use echolocation to locate prey and navigate through the water by emitting sound waves that bounce off objects and return as echoes. The dolphins interpret these echoes to determine the location and size of objects.' },
  { question: 'How do rays protect themselves?', reply: 'Many rays have venomous spines located on their tails that they can use to defend themselves. They also have flattened bodies that allow them to hide in the sand, avoiding predators.' },
  { question: 'How do sharks detect their prey?', reply: 'Sharks use their keen sense of smell to detect blood in the water. They also use electroreception through specialized organs called ampullae of Lorenzini, which can sense the electrical signals produced by other animals.' },
  { question: 'How do sea urchins defend themselves?', reply: 'Sea urchins have sharp, spiny armor on their bodies that act as a defense mechanism. These spines can deter predators and, in some species, are also used to deliver a painful sting.' },
  { question: 'How do squids reproduce?', reply: 'Squids reproduce sexually. Males transfer sperm to females using a specialized arm called a hectocotylus. Females then lay fertilized eggs, which hatch into larvae that grow into adult squid.' },
  { question: 'How do coral reefs provide food?', reply: 'Coral reefs provide food through their complex ecosystem. Algae inside coral polyps photosynthesize, providing nutrients to the corals. These nutrients support a wide range of marine life, from small fish to large predators.' },
  { question: 'How do humpback whales communicate?', reply: 'Humpback whales communicate through songs, which can last up to 20 minutes and can be heard over long distances. These songs are used during mating seasons and may serve other social functions.' },
  { question: 'How do jellyfish find food?', reply: 'Jellyfish use their long, stinging tentacles to capture small fish, plankton, and other prey. The tentacles contain venom that paralyzes and immobilizes the prey, which is then brought to the jellyfish’s mouth for digestion.' },
  { question: 'How do narwhals use their tusks?', reply: 'Narwhals use their long, spiral tusks for communication, as a display of dominance, and potentially for detecting changes in the water’s temperature and pressure. The tusk is actually an elongated tooth.' },
  { question: 'How do sea snakes hunt for food?', reply: 'Sea snakes hunt for small fish and eels. They have venomous bites to immobilize their prey, and some species can stay underwater for long periods of time while hunting.' },
  { question: 'How do anemones catch their prey?', reply: 'Anemones use their stinging tentacles to capture prey, such as small fish and crustaceans. The venom in their tentacles paralyzes the prey, allowing the anemone to move it toward its mouth for digestion.' },
  { question: 'How do sea urchins move?', reply: 'Sea urchins move using their tube feet, which are part of their water vascular system. These tube feet are extended from the underside of their bodies, and they move in a slow, coordinated fashion across the ocean floor.' },
  { question: 'How do dolphins breathe?', reply: 'Dolphins breathe air through a blowhole located on top of their heads. They must surface regularly to exhale and inhale, unlike fish, which use gills to extract oxygen from the water.' },
  { question: 'How do sea turtles find their way home?', reply: 'Sea turtles use the Earth’s magnetic field to navigate across oceans. They imprint the magnetic signature of their birth location, which helps them return to the same area to nest many years later.' },
  { question: 'How do octopuses communicate?', reply: 'Octopuses communicate using body language, including changes in skin color and texture. They can also use their arms to signal intentions, express aggression, or attract mates.' },
  { question: 'How do jellyfish move?', reply: 'Jellyfish move by contracting and relaxing their bell-shaped bodies, forcing water through their system and propelling themselves forward. This method of movement is called jet propulsion.' },
  { question: 'How do narwhals navigate?', reply: 'Narwhals navigate using the Earth’s magnetic field and possibly through their echolocation abilities, helping them navigate the cold waters of the Arctic and locate food sources or mates.' },
  { question: 'How do sea turtles protect their eggs?', reply: 'Sea turtles protect their eggs by burying them in sand or dirt on beaches. After laying their eggs, the mother leaves them to incubate, relying on the sands temperature to help with the hatching process.' },
  { question: 'How do octopuses protect themselves from predators?', reply: 'Octopuses protect themselves by using camouflage to blend into their surroundings. They can also eject ink to create a smokescreen that confuses predators while they escape.' },
  { question: 'How do dolphins avoid predators?', reply: 'Dolphins avoid predators like sharks by swimming in groups, using their speed and agility to outmaneuver them. They also employ defensive tactics, such as using their powerful tails to strike out at threats.' },
  { question: 'How do whales navigate?', reply: 'Whales navigate using echolocation, relying on sound waves that bounce off objects in the water. They also may use the Earths magnetic field and landmarks, such as underwater topography.' },
  { question: 'How do squids avoid predators?', reply: 'Squids avoid predators by using their speed and agility to escape. They can also eject ink, which creates a dark cloud that helps them evade attackers.' },
  { question: 'How do sea otters use kelp?', reply: 'Sea otters use kelp forests to anchor themselves while resting. They wrap themselves in kelp to avoid being swept away by currents, allowing them to stay in one place and stay safe.' },
  ];

// Post endpoint for chatbot interaction
app.post('/api/chat', (req, res) => {
  const { message } = req.body;

  // Default reply if no match is found
  let reply = "Sorry, the prompt you are searching for hasn't been trained yet!";

  // Match the message with the questions in the dataset
  const matchedQA = questionsAndAnswers.find(qa =>
    message.toLowerCase().includes(qa.question.toLowerCase())
  );

  // If a match is found, send the corresponding reply
  if (matchedQA) {
    reply = matchedQA.reply;
  } else {
    // Fallback if no match is found
    reply = "I didn't quite understand that. Could you please rephrase or ask something else?";
  }

  // Send the response back to the client
  res.json({ reply });
});

const PORT = 5000;
app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
